services:
  - type: web
    name: ai-finance-agent
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY_HERE